import { StyleSheet } from 'react-native'
import type { FormStyles, ThemeColors } from '../theme'
import { radius, spacing } from '../theme'

export function createUiStyles(colors: ThemeColors, formStyles: FormStyles) {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: colors.white },
    flex: { flex: 1 },
    scroll: {
      padding: spacing.screen,
      paddingTop: spacing.xl,
    },
    loading: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.white },
    backBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingVertical: spacing.sm,
      marginBottom: spacing.md,
    },
    backText: { fontSize: 15, fontWeight: '500', color: colors.black },
    btnContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.sm,
      flexWrap: 'nowrap',
    },
    btnContentFull: { width: '100%' },
    btnPrimary: {
      backgroundColor: colors.black,
      paddingVertical: 16,
      paddingHorizontal: 24,
      borderRadius: radius.pill,
      alignItems: 'center',
    },
    btnPrimaryText: { color: colors.white, fontSize: 16, fontWeight: '600', flexShrink: 0 },
    btnPrimaryCompact: {
      paddingVertical: 14,
      paddingHorizontal: 18,
    },
    btnPrimaryTextCompact: {
      fontSize: 14,
    },
    btnSuccess: {
      backgroundColor: colors.green,
      paddingVertical: 16,
      paddingHorizontal: 28,
      borderRadius: radius.pill,
      alignItems: 'center',
    },
    btnSuccessText: { color: colors.white, fontSize: 16, fontWeight: '600' },
    btnOutline: {
      borderWidth: 1,
      borderColor: colors.black,
      paddingVertical: 16,
      paddingHorizontal: 28,
      borderRadius: radius.pill,
      alignItems: 'center',
    },
    btnOutlineText: { color: colors.black, fontSize: 16, fontWeight: '600' },
    btnOutlineDisabled: { borderColor: colors.gray200, backgroundColor: colors.gray50 },
    btnOutlineTextDisabled: { color: colors.gray400 },
    btnGhost: {
      borderWidth: 1,
      borderColor: colors.gray200,
      paddingVertical: 16,
      borderRadius: radius.pill,
      alignItems: 'center',
    },
    btnGhostText: { color: colors.gray600, fontSize: 16, fontWeight: '600' },
    btnFull: { width: '100%' },
    btnDisabled: { opacity: 0.4 },
    btnPressed: { opacity: 0.85 },
    methodTabs: {
      flexDirection: 'row',
      backgroundColor: colors.gray75,
      borderRadius: radius.pill,
      padding: 5,
      minHeight: 56,
      marginBottom: spacing.xl,
    },
    methodTab: {
      flex: 1,
      minHeight: 46,
      paddingVertical: 14,
      paddingHorizontal: spacing.md,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: radius.pill,
    },
    methodTabContent: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    methodTabActive: { backgroundColor: colors.black },
    methodTabText: { fontSize: 15, fontWeight: '600', color: colors.gray500 },
    methodTabTextActive: { color: colors.white },
    choiceChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      minHeight: 48,
      paddingHorizontal: 20,
      paddingVertical: 14,
      borderRadius: radius.pill,
      backgroundColor: colors.gray50,
    },
    choiceChipCompact: {
      minHeight: 34,
      paddingHorizontal: 12,
      paddingVertical: 8,
      gap: 5,
    },
    choiceChipOutline: {
      backgroundColor: colors.white,
      borderWidth: 1,
      borderColor: colors.gray100,
    },
    choiceChipFilled: {
      backgroundColor: colors.black,
    },
    choiceChipOutlineSelected: {
      borderColor: colors.black,
      borderWidth: 1.5,
      backgroundColor: colors.white,
    },
    choiceChipText: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.gray600,
    },
    choiceChipTextCompact: { fontSize: 13 },
    choiceChipTextFilled: { color: colors.white },
    choiceChipTextSelected: { color: colors.black },
    optionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.md,
      paddingVertical: spacing.md,
      minHeight: 56,
    },
    optionRadio: {
      width: 26,
      height: 26,
      borderRadius: 13,
      borderWidth: 2,
      borderColor: colors.gray200,
      alignItems: 'center',
      justifyContent: 'center',
    },
    optionRadioSelected: { borderColor: colors.black },
    optionRadioDot: {
      width: 14,
      height: 14,
      borderRadius: 7,
      backgroundColor: colors.black,
    },
    optionCopy: { flex: 1, gap: 2 },
    optionLabel: { fontSize: 16, fontWeight: '600', color: colors.black },
    optionSub: { fontSize: 14, color: colors.gray500, lineHeight: 20 },
    brandSwitch: {
      transform: [{ scaleX: 1.08 }, { scaleY: 1.08 }],
    },
    saveFooter: {
      gap: spacing.sm,
      paddingTop: spacing.md,
      borderTopWidth: 1,
      borderTopColor: colors.gray100,
    },
    saveFooterHint: {
      fontSize: 13,
      color: colors.gray500,
      lineHeight: 18,
      textAlign: 'center',
    },
    saveFooterSavedRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.sm,
    },
    saveFooterSavedText: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.green,
    },
    stickySaveBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.md,
      paddingHorizontal: spacing.screen,
      paddingVertical: spacing.md,
      backgroundColor: colors.white,
      borderTopWidth: 1,
      borderTopColor: colors.gray100,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 8,
    },
    stickySaveText: { flex: 1, fontSize: 14, fontWeight: '600', color: colors.gray600 },
    statusBadge: {
      alignSelf: 'flex-start',
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: radius.pill,
      borderWidth: 1,
    },
    statusBadgeText: { fontSize: 11, fontWeight: '700', letterSpacing: 0.3 },
    status_pending: { backgroundColor: colors.gray50, borderColor: colors.gray200 },
    statusText_pending: { color: colors.gray600 },
    status_accepted: { backgroundColor: colors.greenBg, borderColor: 'rgba(5,148,79,0.25)' },
    statusText_accepted: { color: colors.green },
    status_declined: { backgroundColor: colors.gray50, borderColor: 'rgba(193,53,21,0.2)' },
    statusText_declined: { color: colors.danger },
    status_paid: { backgroundColor: colors.greenBg, borderColor: 'rgba(5,148,79,0.25)' },
    statusText_paid: { color: colors.green },
    status_awaiting: { backgroundColor: colors.gray50, borderColor: colors.gray200 },
    statusText_awaiting: { color: colors.gray600 },
    status_drying: { backgroundColor: colors.gray50, borderColor: colors.black },
    statusText_drying: { color: colors.black },
    status_ready: { backgroundColor: colors.black, borderColor: colors.black },
    statusText_ready: { color: colors.white },
    status_neutral: { backgroundColor: colors.gray50, borderColor: colors.gray100 },
    statusText_neutral: { color: colors.gray600 },
    stepRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: spacing.lg, gap: 2 },
    stepItem: { flex: 1, alignItems: 'center', position: 'relative' },
    stepDot: {
      width: 22,
      height: 22,
      borderRadius: 11,
      borderWidth: 2,
      borderColor: colors.gray200,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.white,
      marginBottom: 6,
    },
    stepDotDone: { backgroundColor: colors.black, borderColor: colors.black },
    stepDotActive: { borderColor: colors.black, borderWidth: 2.5 },
    stepLabel: { fontSize: 10, fontWeight: '600', color: colors.gray400, textAlign: 'center' },
    stepLabelActive: { color: colors.black },
    stepLine: {
      position: 'absolute',
      top: 10,
      left: '55%',
      right: '-45%',
      height: 2,
      backgroundColor: colors.gray200,
      zIndex: -1,
    },
    stepLineDone: { backgroundColor: colors.black },
    appInput: { ...formStyles.input },
    appInputMultiline: { ...formStyles.inputMultiline },
    passwordRow: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.gray200,
      borderRadius: radius.sm,
      backgroundColor: colors.white,
      overflow: 'hidden',
    },
    passwordInput: {
      flex: 1,
      padding: 16,
      fontSize: 16,
      color: colors.black,
      backgroundColor: colors.white,
    },
    passwordToggle: {
      paddingHorizontal: 14,
      paddingVertical: 16,
      justifyContent: 'center',
      alignItems: 'center',
    },
  })
}
